### PR TITLE
Django 1.9 compatibility

### PR DESCRIPTION
**Pull request by olarin**

### CODE REVIEW

**Comment by brutasse** [comment]
Thanks @olarin!

`{% load url from future %}` is not needed since Django 1.5… We can probably drop them completely, what do you think?

**Comment by olarin** [comment]
I think, we can. Support of Django 1.4 was ended 5 moths ago.

**Comment by brutasse** [comment]
Great. Do you want to update this pr?

**Comment by olarin** [comment]
Done.

**Comment by brutasse** [comment]
:tada: Thanks @olarin!

**Comment by brutasse** [comment]
0.3.0 is up on PyPI.

**Pull request merged**
