### PR TITLE
Fix a bad decode error on Python 3

### LINKED ISSUE #15: Stacktrace in python3
Seeing this on the dashboard when it tries to do the background refresh.

```
GET /admin/rq/ HTTP/1.1
Host: <something>
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Referer: http://<something>/admin/rq/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie:  cookie=hidden;  sessionid=hidden; csrftoken=n6UhHNt4ILkJMiEQtfqqkNDeeA08PgiS
```

```
ERROR:django.request:Internal Server Error: /admin/rq/
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django_rq_dashboard/views.py", line 89, in dispatch
    return super(SuperUserMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/generic/base.py", line 158, in get
    return self.render_to_response(context)
  File "/usr/lib/python3.5/site-packages/django_rq_dashboard/views.py", line 117, in render_to_response
    'workers': [serialize_worker(w) for w in context['workers']],
  File "/usr/lib/python3.5/site-packages/django_rq_dashboard/views.py", line 117, in <listcomp>
    'workers': [serialize_worker(w) for w in context['workers']],
  File "/usr/lib/python3.5/site-packages/django_rq_dashboard/views.py", line 60, in serialize_worker
    state=worker.get_state().decode('utf-8'),
AttributeError: 'str' object has no attribute 'decode'
```

requirements:
django-rq-dashboard=0.3.0
Django==1.9.7
rq==0.6.0

python 3.5.1

Thanks for the project!

### PR DESCRIPTION
**Pull request by jleclanche**
Fixes #15

### CODE REVIEW

**Comment by jleclanche** [comment]
@brutasse Hey can you merge this please? I can help with maintenance of the project if you want to give me commit access.

**Comment by brutasse** [comment]
Ah, got it -- it's because of this commit that decoding fails. State is now always text.

https://github.com/nvie/rq/commit/f9978bc27cd81eb736ef02c0e3ba6e6a2751c85e

Could you remove the isinstance check? Just do `state=worker.get_state()` and it should work fine on all python versions.

Thanks!

**Comment by jleclanche** [comment]
@brutasse Done!

Is the project still being maintained? We don't use the dashboard much, but we do use it, so I might end up contributing more if it is.

**Comment by brutasse** [comment]
@jleclanche thanks! Yes, I'm still using it and maintaining it. Not catching up very often with RQ updates though :)

Version 0.3.1 is available on PyPI.

**Pull request merged**
